apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: dracan/dddweb:0.2
        ports:
        - containerPort: 80
